# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install numpy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy>=1.16.2
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.5
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0
