# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install virtualenv
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
      - run:
          name: Install numpy
          command: |
            pip install numpy
      - run:
          name: Install sigpropy and dependencies
          command: |
            pip install -e .
      - run:
          name: Run tests
          command: |
            cd test
            python -m unittest

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.5
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0
