version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@7.6.7
  codecov: codecov/codecov@1.0.2

workflows:
  build:
    jobs:
      - test-36:
          context:
            - docker          
      - test-37:
          context:
            - docker
      - test-38:
          context:
            - docker
      - test-39:
          context:
            - docker

jobs:
  test-36: &test-template
    docker:
      - image: circleci/python:3.6.14
        auth:
          username: jpvantassel
          password: $DOCKER_PASS
    working_directory: ~/sigpropy
    steps:
      - checkout
      # - restore_cache:
      #     key: pycache-{{ .Branch }}-{{ checksum "requirements.txt" }}  
      - run:
          name: Install Requirements
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install numpy
            pip install -r requirements.txt
      # - save_cache:
      #     key: pycache-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - "venv"
      - run:
          name: Install sigpropy
          command: |
            . venv/bin/activate
            pip install -e .[dev]
      - run:
          name: Test
          command: |
            . venv/bin/activate
            cd test
            coverage run --source=../sigpropy -m unittest
      - run:
          name: Create Coverage Report
          command: |
            . venv/bin/activate
            mkdir test-results
            mv test/.coverage test-results
            cd test-results
            coverage xml -o cobertura.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload:
          file: test-results/cobertura.xml
      - coverage-reporter/send_report

  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.11
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-38:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.11
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-39:
    <<: *test-template
    docker:
      - image: circleci/python:3.9.6
        auth:
          username: jpvantassel
          password: $DOCKER_PASS