# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@7.6.7
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
      - send-coverage-report
jobs:
  send-coverage-report:
    steps:
      - checkout
      - run:
          name: Prepare Results
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install numpy
            pip install -e .[dev]
            cd test
            coverage run --source=../sigpropy -m unittest
            cd ..
            mkdir test-results
            mv test/.coverage test-results
            cd test-results
            coverage xml -o coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - coverage-reporter/send_report

  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            virtualenv venv
            . venv/bin/activate
            mkdir test-results
      - run:
          name: Install numpy
          command: |
            . venv/bin/activate
            pip install numpy
      - run:
          name: Install sigpropy and dependencies
          command: |
            . venv/bin/activate
            pip install -e .[dev]
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd test
            coverage run --source=../sigpropy -m unittest
      - run:
          name: Create coverage xml
          command: |
            . venv/bin/activate
            mv test/.coverage test-results
            cd test-results
            coverage xml -o coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run:
          name: Call Codecov
          command: |
            . venv/bin/activate
            pip install codecov
            codecov
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.5
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0
